# Synthetic Data Generation for RAG Evaluation

Session 1 built a vector RAG application over a cat health guideline PDF. This
session creates an evaluation dataset for that application and uses the dataset
to compare two retrieval configurations. All generation, embedding, RAG, and
judge requests are routed through Vercel AI Gateway.

The workflow is:

~~~text
corpus -> knowledge graph -> synthetic examples -> human review
       -> LangSmith dataset -> baseline and candidate experiments
~~~

Synthetic examples reduce the cost of getting started, but generated references
are not automatically ground truth. We will inspect and curate them before using
them as evaluation targets.

> This is an educational cat health exercise, not veterinary advice. Generated
> questions and answers must not be used to diagnose, prescribe, or replace a
> veterinarian.

## Learning Outcomes

By the end of this notebook, you will be able to:

- Explain how Ragas builds a knowledge graph for test data generation.
- Distinguish single-hop specific, multi-hop specific, and multi-hop abstract queries.
- Generate and review synthetic questions, reference contexts, and reference answers.
- Route generation, embeddings, RAG, and judge calls through Vercel AI Gateway.
- Upload reviewed examples to a LangSmith dataset.
- Evaluate answer correctness, answer groundedness, and retrieval relevance.
- Run a controlled RAG experiment that changes one variable at a time.

## Table of Contents

- **Breakout Room #1: Synthetic Test Data with Ragas**
  - Task 1: Environment Setup
  - Task 2: Load the Cat Health Corpus
  - Task 3: Build and Enrich a Knowledge Graph
  - Task 4: Inspect the Query Distribution
  - Task 5: Generate and Inspect a Synthetic Test Set
  - Activity #1: Review and Curate the Dataset
- **Breakout Room #2: RAG Evaluation with LangSmith**
  - Task 6: Create a LangSmith Dataset
  - Task 7: Build a Baseline RAG Application
  - Task 8: Define RAG Evaluators
  - Task 9: Run the Baseline Experiment
  - Task 10: Change One Retrieval Variable and Re-Evaluate
  - Activity #2: Compare, Diagnose, and Iterate
  - Advanced Build: Add Robustness and Adversarial Cases

---
# Breakout Room #1
## Synthetic Test Data with Ragas

Ragas uses the source corpus to create a richer representation of its topics and
relationships. Query synthesizers then select scenarios from that representation
and generate questions plus reference answers.

The knowledge graph is a generation aid. It is not the graph used by the RAG
application in Breakout Room #2.

## Task 1: Environment Setup

From the <code>05_Synthetic_Data_Generation_for_RAG_Evals</code> folder:

~~~bash
uv sync
~~~

Then select the environment created by uv as this notebook's kernel.

Required accounts:

- Vercel AI Gateway for generation, embeddings, the RAG answer model, and judges
- LangSmith for the dataset and experiments

A direct OpenAI API key is not required. The OpenAI SDK is used only as a
protocol-compatible client pointed at Vercel AI Gateway.

The default synthetic test set is intentionally small. Ragas generation and
LLM-as-judge evaluation both make multiple model calls, so start small and scale
only after inspecting quality.

### Imports

In [1]:
from __future__ import annotations

import os
from collections import Counter
from getpass import getpass
from importlib.metadata import version
from pathlib import Path
from uuid import uuid4

import instructor
from IPython.display import display
from openai import OpenAI
from pydantic import BaseModel, field_validator

from langchain_community.document_loaders import PyPDFLoader
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_qdrant import QdrantVectorStore
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langsmith import Client, evaluate
from openevals.llm import create_llm_as_judge
from openevals.prompts import (
    CORRECTNESS_PROMPT,
    RAG_GROUNDEDNESS_PROMPT,
    RAG_RETRIEVAL_RELEVANCE_PROMPT,
)

from ragas.embeddings import embedding_factory
from ragas.llms import llm_factory
from ragas.run_config import RunConfig
from ragas.testset import TestsetGenerator
from ragas.testset.graph import KnowledgeGraph, Node, NodeType
from ragas.testset.synthesizers import (
    MultiHopAbstractQuerySynthesizer,
    MultiHopSpecificQuerySynthesizer,
    SingleHopSpecificQuerySynthesizer,
    default_query_distribution,
)
from ragas.testset.transforms import (
    CustomNodeFilter,
    SummaryExtractor,
    apply_transforms,
    default_transforms_for_prechunked,
)

/Users/ltewari/AI_makerspace/AI_Course/The-AI-Engineering-Certification-v1.0/05_Synthetic_Data_Generation_for_RAG_Evals/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### API Keys, Models, and Cost Controls

The notebook reads model names and budgets from environment variables so you can
tune cost without editing every cell. Vercel AI Gateway exposes an
OpenAI-compatible endpoint, so the OpenAI and LangChain clients only need a
different API key, base URL, and provider-qualified model ID.

See the [Vercel AI Gateway Python documentation](https://vercel.com/docs/ai-gateway/sdks-and-apis/python)
for the current authentication and endpoint details.

LangSmith uses <code>LANGSMITH_TRACING</code>. The older
<code>LANGCHAIN_TRACING_V2</code> name from the source notebook is no longer
needed here.

In [2]:
gateway_api_key = (
    os.environ.get("AI_GATEWAY_API_KEY")
    or os.environ.get("VERCEL_OIDC_TOKEN")
)

if not gateway_api_key:
    gateway_api_key = getpass("Vercel AI Gateway API Key: ")
    os.environ["AI_GATEWAY_API_KEY"] = gateway_api_key

if not os.environ.get("LANGSMITH_API_KEY"):
    os.environ["LANGSMITH_API_KEY"] = getpass("LangSmith API Key: ")

os.environ.setdefault("LANGSMITH_TRACING", "true")
os.environ.setdefault(
    "LANGSMITH_PROJECT",
    "aim-session-5-synthetic-rag-evals",
)

GATEWAY_BASE_URL = os.environ.get(
    "AI_GATEWAY_BASE_URL",
    "https://ai-gateway.vercel.sh/v1",
)
GENERATOR_MODEL_NAME = os.environ.get(
    "AIM_GENERATOR_MODEL",
    "openai/gpt-5.4-mini",
)
RAG_MODEL_NAME = os.environ.get(
    "AIM_RAG_MODEL",
    "openai/gpt-5.4-mini",
)
JUDGE_MODEL_NAME = os.environ.get(
    "AIM_JUDGE_MODEL",
    "openai/gpt-5.4-mini",
)
EMBEDDING_MODEL_NAME = os.environ.get(
    "AIM_EMBEDDING_MODEL",
    "openai/text-embedding-3-small",
)
TESTSET_SIZE = int(os.environ.get("AIM_TESTSET_SIZE", "6"))
MAX_CONCURRENCY = int(os.environ.get("AIM_MAX_CONCURRENCY", "2"))

gateway_models = {
    "generator": GENERATOR_MODEL_NAME,
    "rag": RAG_MODEL_NAME,
    "judge": JUDGE_MODEL_NAME,
    "embedding": EMBEDDING_MODEL_NAME,
}
for role, model_name in gateway_models.items():
    if "/" not in model_name:
        raise ValueError(
            f"{role} model must use a provider-qualified AI Gateway ID: "
            f"{model_name!r}"
        )

print(f"Ragas: {version('ragas')}")
print(f"LangSmith: {version('langsmith')}")
print(f"AI Gateway: {GATEWAY_BASE_URL}")
print(f"Generator model: {GENERATOR_MODEL_NAME}")
print(f"RAG model: {RAG_MODEL_NAME}")
print(f"Judge model: {JUDGE_MODEL_NAME}")
print(f"Embedding model: {EMBEDDING_MODEL_NAME}")
print(f"Synthetic examples: {TESTSET_SIZE}")
print(f"LangSmith tracing: {os.environ['LANGSMITH_TRACING']}")

Ragas: 0.4.4.dev8+g298b68274
LangSmith: 0.8.16
AI Gateway: https://ai-gateway.vercel.sh/v1
Generator model: openai/gpt-5.4-mini
RAG model: openai/gpt-5.4-mini
Judge model: openai/gpt-5.4-mini
Embedding model: openai/text-embedding-3-small
Synthetic examples: 6
LangSmith tracing: true

## Task 2: Load the Cat Health Corpus

The corpus is the bundled 2021 AAHA/AAFP Feline Life Stage Guidelines PDF used
in Session 1. <code>PyPDFLoader</code> extracts one LangChain document per page,
including page metadata that survives later chunking.

This gives the generator multiple related units to connect:

- hydration and urinary signs
- preventive care and senior care
- dental pain and behavior changes
- monitoring and emergency escalation

In [3]:
corpus_path = Path("data/cat_health_guidelines.pdf")

if not corpus_path.exists():
    raise FileNotFoundError(
        f"Expected the course corpus at {corpus_path.resolve()}"
    )

pdf_loader = PyPDFLoader(str(corpus_path))
source_documents = pdf_loader.load()
source_documents = [
    document
    for document in source_documents
    if len(document.page_content.strip()) >= 200
]

for index, document in enumerate(source_documents):
    page_number = int(document.metadata.get("page", index)) + 1
    document.metadata.update(
        {
            "source": corpus_path.name,
            "document_type": "feline_life_stage_guidelines",
            "page_number": page_number,
        }
    )

print(f"Loaded {len(source_documents)} text-containing PDF pages")
for document in source_documents[:5]:
    page_number = document.metadata["page_number"]
    print(
        f"- page {page_number}: "
        f"{len(document.page_content)} characters"
    )

Loaded 20 text-containing PDF pages
- page 1: 4913 characters
- page 2: 2084 characters
- page 3: 5955 characters
- page 6: 5673 characters
- page 7: 3588 characters

Inspect one PDF page and its metadata. The metadata is useful for debugging,
trace inspection, and explaining where a retrieved chunk came from.

In [4]:
sample_document = source_documents[19]

print(sample_document.metadata)
print()
print(sample_document.page_content[:800])

{'producer': 'Acrobat Distiller 10.0.0 (Windows)', 'creator': 'Adobe InDesign CS6 (Windows)', 'creationdate': '2021-02-02T08:52:15-05:00', 'author': '7123', 'moddate': '2021-02-02T07:53:51-07:00', 'title': 'djs_jaaha_56_5_COVER.indd', 'source': 'cat_health_guidelines.pdf', 'total_pages': 22, 'page': 21, 'page_label': '22', 'document_type': 'feline_life_stage_guidelines', 'page_number': 22}

130. van Bree FPJ, Bokken GCAM, Mineur R, et al. Zoonotic bacteria and
parasites found in raw meat-based diets for cats and dogs. V et Rec2018;
182:50. DOI: 10.1136/vr.104535.
131. Carney HC, W ard CR, Bailey SJ, et al. 2016 AAFP guidelines for the
management of feline hyperthyroidism.JF e l i n eM e dS u r g2016;18:400–16.
132. Sparkes AH, Caney S, Chalhoub S, et al. ISFM consensus guidelines on
the diagnosis and management of feline chronic kidney disease. J Feline
Med Surg 2016;18:219–39.
133. Behrend E, Holford A, Lathan P , et al. 2018 AAHA diabetes manage-
ment guidelines for dogs and cats. J Am Anim Hosp Assoc 2018;54:1–21.
Available at: https://www.aaha.org/diabetes.
134. AAFP .2019 Diabetes Educational T oolkit. Available at: catvets.com/diabetes.
135. Sparkes AH, Cannon M, Church

## Task 3: Build and Enrich a Knowledge Graph

The unrolled workflow makes the generation stages visible:

1. Treat each text-containing PDF page as a pre-chunked Ragas node.
2. Run Ragas extractors, embeddings, and relationship builders.
3. Save the graph so expensive enrichment can be reused.

Ragas remains responsible for graph enrichment and synthetic generation. The
newer pinned Ragas build exposes an official Instructor mode parameter, so its
LLM factory can use AI Gateway tool calls directly without custom wrappers.

In [5]:
gateway_client = OpenAI(
    api_key=gateway_api_key,
    base_url=GATEWAY_BASE_URL,
)

generator_llm = llm_factory(
    GENERATOR_MODEL_NAME,
    provider="openai",
    client=gateway_client,
    mode=instructor.Mode.TOOLS,
    max_tokens=4096,
)
# Provider-qualified Gateway IDs bypass Ragas's GPT-5 parameter detection.
# Keep only the token limit supported by the Gateway route. max_retries is
# consumed locally by Instructor and is not sent to AI Gateway.
generator_llm.model_args = {
    "max_tokens": 4096,
    "max_retries": 3,
}

generator_embeddings = embedding_factory(
    "openai",
    model=EMBEDDING_MODEL_NAME,
    client=gateway_client,
)

ragas_run_config = RunConfig(
    timeout=180,
    max_retries=3,
    max_wait=30,
    max_workers=MAX_CONCURRENCY,
)

/var/folders/52/7xdypc117w3dck3rxq9nvp9r0000gp/T/ipykernel_94348/1199448542.py:21: DeprecationWarning: Importing embedding_factory from ragas.embeddings is deprecated. Import directly from ragas.embeddings.base or use modern providers: from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = embedding_factory(

Before building the graph, make one small structured-output request through
Ragas. This catches gateway authentication, model availability, and tool-calling
incompatibilities without waiting for every PDF page to retry.

In [6]:
class GatewayToolCallCheck(BaseModel):
    status: str


class NonEmptySummary(BaseModel):
    text: str

    @field_validator("text")
    @classmethod
    def require_text(cls, value):
        value = value.strip()
        if not value:
            raise ValueError("summary text cannot be empty")
        return value


gateway_check = generator_llm.generate(
    "Use the required tool with a short, non-empty status message.",
    GatewayToolCallCheck,
)
if not gateway_check.status.strip():
    raise RuntimeError("AI Gateway returned an empty tool-call check")

print(f"AI Gateway tool-based structured output: {gateway_check.status}")

AI Gateway tool-based structured output: ok

In [7]:
def build_prechunked_knowledge_graph(chunks):
    return KnowledgeGraph(
        nodes=[
            Node(
                type=NodeType.CHUNK,
                properties={
                    "page_content": chunk.page_content,
                    "document_metadata": dict(chunk.metadata),
                },
            )
            for chunk in chunks
            if chunk.page_content.strip()
        ]
    )


generation_chunks = list(source_documents)
knowledge_graph = build_prechunked_knowledge_graph(generation_chunks)

print(f"Ragas input chunks: {len(generation_chunks)}")
print(knowledge_graph)

Ragas input chunks: 20
KnowledgeGraph(nodes: 20, relationships: 0)

### Apply Ragas Transforms

Because the PDF loader already gives us coherent page-level chunks, use Ragas'
built-in pre-chunked transform pipeline. It skips headline extraction and
splitting, then applies Ragas summaries, embeddings, themes, named entities,
and relationship builders directly to the PDF pages. The parent-child node
filter is omitted because these page chunks intentionally have no parent nodes.
A non-empty output constraint makes Instructor retry blank Ragas summaries before
the built-in embedding transform runs.

In [8]:
knowledge_graph = build_prechunked_knowledge_graph(generation_chunks)
transforms = [
    transform
    for transform in default_transforms_for_prechunked(
        llm=generator_llm,
        embedding_model=generator_embeddings,
    )
    if not isinstance(transform, CustomNodeFilter)
]

summary_transform = next(
    transform
    for transform in transforms
    if isinstance(transform, SummaryExtractor)
)
summary_transform.prompt.output_model = NonEmptySummary

print("Ragas transform pipeline:")
for transform in transforms:
    nested = getattr(transform, "transformations", None)
    if nested is None:
        print(f"- {type(transform).__name__}")
    else:
        names = ", ".join(type(item).__name__ for item in nested)
        print(f"- Parallel({names})")

for transform in transforms:
    apply_transforms(
        knowledge_graph,
        transform,
        run_config=ragas_run_config,
    )
    if isinstance(transform, SummaryExtractor):
        empty_summary_nodes = [
            node
            for node in knowledge_graph.nodes
            if not str(node.get_property("summary") or "").strip()
        ]
        if empty_summary_nodes:
            raise RuntimeError(
                "Ragas did not produce non-empty summaries for "
                f"{len(empty_summary_nodes)} PDF chunks"
            )

print(knowledge_graph)

Ragas transform pipeline:
- SummaryExtractor
- Parallel(EmbeddingExtractor, ThemesExtractor, NERExtractor)
- Parallel(CosineSimilarityBuilder, OverlapScoreBuilder)

Applying SummaryExtractor: 100%|██████████| 20/20 [00:36<00:00,  1.83s/it]
Applying [EmbeddingExtractor, ThemesExtractor, NERExtractor]:   0%|          | 0/60 [00:00<?, ?it/s]/Users/ltewari/AI_makerspace/AI_Course/The-AI-Engineering-Certification-v1.0/05_Synthetic_Data_Generation_for_RAG_Evals/.venv/lib/python3.12/site-packages/ragas/testset/transforms/base.py:198: UserWarning: Using sync embedding model OpenAIEmbeddings in async context. This may impact performance. Consider using an async-compatible embedding model for better performance.
  property_name, property_value = await self.extract(node)
Applying [EmbeddingExtractor, ThemesExtractor, NERExtractor]: 100%|██████████| 60/60 [01:09<00:00,  1.16s/it]
Applying [CosineSimilarityBuilder, OverlapScoreBuilder]: 100%|██████████| 2/2 [00:00<00:00, 33.11it/s]

KnowledgeGraph(nodes: 20, relationships: 66)

Inspect the graph at a high level. Different Ragas versions may add different
properties, so the notebook avoids depending on one exact internal schema.

In [9]:
node_type_counts = Counter(str(node.type) for node in knowledge_graph.nodes)

print("Node types:")
for node_type, count in node_type_counts.items():
    print(f"- {node_type}: {count}")

print(f"Relationships: {len(knowledge_graph.relationships)}")

for index, node in enumerate(knowledge_graph.nodes[:3], start=1):
    property_names = sorted(node.properties.keys())
    print(f"Node {index} properties: {property_names}")

Node types:
- NodeType.CHUNK: 20
Relationships: 66
Node 1 properties: ['document_metadata', 'entities', 'page_content', 'summary', 'summary_embedding', 'themes']
Node 2 properties: ['document_metadata', 'entities', 'page_content', 'summary', 'summary_embedding', 'themes']
Node 3 properties: ['document_metadata', 'entities', 'page_content', 'summary', 'summary_embedding', 'themes']

### Save and Reload the Graph

Generated artifacts go in the ignored <code>artifacts/</code> folder so running
the notebook does not add large, machine-generated files to the assignment diff.

In [10]:
artifacts_dir = Path("artifacts")
artifacts_dir.mkdir(exist_ok=True)

knowledge_graph_path = artifacts_dir / "cat_health_knowledge_graph.json"
knowledge_graph.save(str(knowledge_graph_path))

loaded_knowledge_graph = KnowledgeGraph.load(str(knowledge_graph_path))

print(f"Saved graph to {knowledge_graph_path}")
print(loaded_knowledge_graph)

Saved graph to artifacts/cat_health_knowledge_graph.json
KnowledgeGraph(nodes: 20, relationships: 66)

#### ❓ Question #1

What information did the Ragas graph transforms add beyond the original text,
and why are the two relationship types important for multi-hop questions?

##### ✅ Answer

Ragas added structured graph data with entities and relationships, which helps in understanding the context and relationships between different pieces of information. The two relationship types (has_symptom and has_condition) are important for multi-hop questions because they allow the system to trace connections between symptoms and conditions, enabling more complex and nuanced queries.

## Task 4: Inspect the Query Distribution

Ragas can synthesize several kinds of questions:

| Query type | What it tests |
|---|---|
| Single-hop specific | Retrieve one concrete fact or recommendation from one context |
| Multi-hop specific | Combine concrete details from multiple related contexts |
| Multi-hop abstract | Connect broader themes or concepts across contexts |

The distribution is part of the evaluation specification. It determines which
behaviors are common in the generated dataset.

In [11]:
query_distribution = default_query_distribution(
    generator_llm,
    kg=loaded_knowledge_graph,
)

print("Available query synthesizers:")
for synthesizer, weight in query_distribution:
    print(f"- {synthesizer.name}: {weight:.0%}")

distribution_total = sum(weight for _, weight in query_distribution)
print(f"Distribution total: {distribution_total:.2f}")

Available query synthesizers:
- single_hop_specific_query_synthesizer: 33%
- multi_hop_abstract_query_synthesizer: 33%
- multi_hop_specific_query_synthesizer: 33%
Distribution total: 1.00

### Define a Custom Distribution

The default is a sensible starting point, but the mix should reflect the
application behavior you care about. This example emphasizes concrete
single-hop questions while preserving coverage of both multi-hop styles.

Adjust the weights below and assign
<code>query_distribution = custom_query_distribution</code> before Task 5 if
you want the generated dataset to use your mix. We define the distribution here
without generating a second test set, which keeps the worked notebook's cost
bounded.

The default helper filters out synthesizers that the enriched graph cannot
support. If a custom multi-hop run reports that no matching relationships exist,
inspect the graph and use only the synthesizers listed by the default distribution.

In [12]:
custom_query_distribution = [
    (
        SingleHopSpecificQuerySynthesizer(llm=generator_llm),
        0.50,
    ),
    (
        MultiHopSpecificQuerySynthesizer(llm=generator_llm),
        0.30,
    ),
    (
        MultiHopAbstractQuerySynthesizer(llm=generator_llm),
        0.20,
    ),
]

assert abs(
    sum(weight for _, weight in custom_query_distribution) - 1.0
) < 1e-9

for synthesizer, weight in custom_query_distribution:
    print(f"- {synthesizer.name}: {weight:.0%}")

- single_hop_specific_query_synthesizer: 50%
- multi_hop_specific_query_synthesizer: 30%
- multi_hop_abstract_query_synthesizer: 20%

#### ❓ Question #2

Describe the three query types in your own words. Which type do you expect to be
hardest for a basic dense-retrieval RAG application, and why?

##### ✅ Answer

The single_hop query type is the simplest, where the query can be answered with a single, straightforward retrieval from the knowledge base. The multi_hop_specific queries require the system to synthesize information from multiple sources, requiring the system to synthesize information from different parts of the knowledge base. 

The multi_hop_abstract queries are the most complex, as they require the system to synthesize information from multiple sources and generate a response that is not directly stated in the knowledge base.

I expect the multi_hop_abstract query type to be the hardest for a basic dense-retrieval RAG application, as it requires the system to synthesize information from multiple sources and generate a response that is not directly stated in the knowledge base.

## Task 5: Generate and Inspect a Synthetic Test Set

Each generated row contains:

- <code>user_input</code>: the synthetic question
- <code>reference_contexts</code>: source context selected by the generator
- <code>reference</code>: a generated reference answer
- <code>synthesizer_name</code>: the query strategy that produced the row

The reference is generated from selected source context. It is useful, but it
still needs review for accuracy, clarity, safety, and usefulness.

In [13]:
testset_generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
    knowledge_graph=loaded_knowledge_graph,
)

synthetic_testset = testset_generator.generate(
    testset_size=TESTSET_SIZE,
    query_distribution=query_distribution,
    run_config=ragas_run_config,
)

testset_df = synthetic_testset.to_pandas()

display(
    testset_df[
        [
            "user_input",
            "reference",
            "synthesizer_name",
        ]
    ]
)

Generating personas: 100%|██████████| 3/3 [00:06<00:00,  2.15s/it]
Generating Scenarios: 100%|██████████| 3/3 [00:28<00:00,  9.40s/it]
Generating Samples: 100%|██████████| 6/6 [00:12<00:00,  2.09s/it]

,user_input,reference,synthesizer_name
0,What role did Paula Plummer have in the 2021 A...,"Paula Plummer, LVT, VTS (ECC, SAIM), is listed...",single_hop_specific_query_synthesizer
1,Why are life stage assessments important in fe...,A life stage assessment is important because a...,single_hop_specific_query_synthesizer
2,According to the human-cat relationships and c...,The 2021 AAHA/AAFP Feline Life Stage Guideline...,multi_hop_abstract_query_synthesizer
3,How does senior cat care in the aging in cats ...,The guidelines say senior is a life stage in c...,multi_hop_abstract_query_synthesizer
4,According to the American Association of Felin...,The 2021 guidelines organize feline life stage...,multi_hop_specific_query_synthesizer
5,"According to the feline life stage guidelines,...",Each examination visit should include a life s...,multi_hop_specific_query_synthesizer

In [14]:
testset_path = artifacts_dir / "cat_health_synthetic_testset.jsonl"
testset_df.to_json(
    testset_path,
    orient="records",
    lines=True,
    force_ascii=False,
)

print("Examples by synthesizer:")
print(testset_df["synthesizer_name"].value_counts())
print()
print(f"Saved candidate examples to {testset_path}")

Examples by synthesizer:
synthesizer_name
single_hop_specific_query_synthesizer    2
multi_hop_abstract_query_synthesizer     2
multi_hop_specific_query_synthesizer     2
Name: count, dtype: int64

Saved candidate examples to artifacts/cat_health_synthetic_testset.jsonl

### Abstracted Ragas Alternative

The graph-first path above makes each Ragas stage inspectable and lets you save
the enriched graph before generation. Ragas also provides a one-call helper for
content that is already chunked:

~~~python
quick_generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
)
quick_testset = quick_generator.generate_with_chunks(
    chunks=generation_chunks,
    testset_size=TESTSET_SIZE,
    transforms=transforms,
    run_config=ragas_run_config,
)
~~~

This alternative is shown rather than executed so the notebook does not repeat
the same billable graph enrichment and test-set generation.

#### ❓ Question #3

What are the tradeoffs between the unrolled and one-call Ragas generation paths?
When would you choose each one?

##### ✅ Answer

The tradeoffs between the unrolled and one-call Ragas generation paths are as follows:

- **Unrolled Path**: More control over each step, easier to debug, but more code to write and maintain.
- **One-call Path**: Less code to write and maintain, but less control over each step and harder to debug.

Choose the unrolled path when we need more control over each step or when debugging. Choose the one-call path when we want less code to write and maintain.

## 🏗️ Activity #1: Review and Curate the Dataset

Review every generated row before uploading it.

For each example, check:

1. Is the question answerable from the reference contexts?
2. Is the reference answer fully supported by those contexts?
3. Is the wording natural for a plausible user?
4. Does the example duplicate another row?
5. Does it preserve the corpus's medical-safety boundaries?

Requirements:

- Remove or repair at least one weak example, if one exists.
- Record why you kept, edited, or removed it.
- Keep the synthesizer name in metadata so you can diagnose query-type failures.

In [15]:
# Activity #1 workspace
#
# Review decisions:
#   Row 0 (index 0) — REMOVED: authorship trivia ("What role did Paula Plummer have...").
#     Not a realistic cat health query; tests document metadata, not RAG health capability.
#   Row 2 (index 2) — REPAIRED: question contained a Ragas graph artifact ("human-cat
#     relationships and communication theme"). Rewritten to natural user phrasing.
#   Row 3 (index 3) — REPAIRED: same artifact pattern ("aging in cats and geriatric care
#     theme"). Rewritten to natural user phrasing.
#   Rows 1, 4, 5 — KEPT: answerable, grounded, natural wording, no safety issues,
#     no duplicates.

approved_testset_df = testset_df.drop(index=[0]).reset_index(drop=True)

approved_testset_df.loc[1, "user_input"] = (
    "According to the 2021 AAHA/AAFP Feline Life Stage Guidelines, "
    "how does the updated guidance on regular feline healthcare support "
    "a lifelong individualized feline healthcare strategy?"
)

approved_testset_df.loc[2, "user_input"] = (
    "How does senior cat care connect to the life-stage strategy and "
    "feline-friendly handling recommendations in the 2021 AAHA/AAFP "
    "Feline Life Stage Guidelines?"
)

review_status = "student_reviewed"

display(
    approved_testset_df[
        [
            "user_input",
            "reference_contexts",
            "reference",
            "synthesizer_name",
        ]
    ]
)

,user_input,reference_contexts,reference,synthesizer_name
0,Why are life stage assessments important in fe...,[Introduction\nThe feline patient ’s life stag...,A life stage assessment is important because a...,single_hop_specific_query_synthesizer
1,According to the 2021 AAHA/AAFP Feline Life St...,"[<1-hop>\n\n44. Reisner IR, Houpt KA, Erb HN, ...",The 2021 AAHA/AAFP Feline Life Stage Guideline...,multi_hop_abstract_query_synthesizer
2,How does senior cat care connect to the life-s...,"[<1-hop>\n\n90. Wichert B, Muller L, Gebert S,...",The guidelines say senior is a life stage in c...,multi_hop_abstract_query_synthesizer
3,According to the American Association of Felin...,[<1-hop>\n\nVETERINARY PRACTICE GUIDELINES\n20...,The 2021 guidelines organize feline life stage...,multi_hop_specific_query_synthesizer
4,"According to the feline life stage guidelines,...","[<1-hop>\n\n10 months, primarily by phone cont...",Each examination visit should include a life s...,multi_hop_specific_query_synthesizer

### 📝 Activity #1 Notes

- **Row 0 removed** — "What role did Paula Plummer have in the 2021 AAHA/AAFP Feline Life Stage Guidelines?" This is authorship trivia drawn from the document header. A cat health RAG user would never ask this; it tests PDF metadata retrieval, not health knowledge. No safety issue, but it fails the plausible-user and health-capability criteria.

- **Row 2 repaired** — Original: "According to the human-cat relationships and communication theme, what does the 2021 AAHA/AAFP Feline Life Stage Guidelines update say...". The phrase "human-cat relationships and communication theme" is a Ragas knowledge-graph label, not natural language. Rewritten to remove the artifact while preserving the intent.

- **Row 3 repaired** — Same issue: "aging in cats and geriatric care theme" is a Ragas graph node label. Rewritten to plain question form.

- **Rows 1, 4, 5 kept** — Natural wording, answerable from reference contexts, reference answers are supported by the PDF, no duplicates, no medical-safety boundary violations (no diagnosis or dosing requests).

- **Safety note** — No generated example asked for a diagnosis, medication dose, or treatment prescription. All five retained examples stay within the corpus's educational scope.

---
# Breakout Room #2
## RAG Evaluation with LangSmith

We will upload the reviewed examples, build one RAG application, and evaluate two
retrieval settings against the same dataset and judges.

Keeping the dataset and evaluators fixed makes the application change easier to
interpret.

## Task 6: Create a LangSmith Dataset

The dataset stores the question as input and the reviewed synthetic answer plus
reference contexts as outputs. Query type and provenance remain metadata.

A unique suffix prevents accidental duplication when the whole notebook is rerun.
For a long-lived team dataset, use a stable name and manage versions deliberately.

In [16]:
def as_string_list(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value]
    if hasattr(value, "tolist"):
        converted = value.tolist()
        if isinstance(converted, list):
            return [str(item) for item in converted]
    return [str(value)]


if review_status != "student_reviewed":
    raise ValueError(
        "Complete Activity #1, curate approved_testset_df, and set "
        "review_status = 'student_reviewed' before uploading."
    )


langsmith_client = Client()
dataset_name = (
    "aim-session-5-cat-health-synthetic-"
    f"{uuid4().hex[:8]}"
)

langsmith_dataset = langsmith_client.create_dataset(
    dataset_name=dataset_name,
    description=(
        "Ragas-generated questions for the AI Makerspace "
        "cat health RAG lesson."
    ),
    metadata={
        "session": 5,
        "source": "ragas",
        "corpus": str(corpus_path),
    },
)

langsmith_examples = []
for _, row in approved_testset_df.iterrows():
    langsmith_examples.append(
        {
            "inputs": {
                "question": str(row["user_input"]),
            },
            "outputs": {
                "answer": str(row["reference"]),
                "reference_contexts": as_string_list(
                    row["reference_contexts"]
                ),
            },
            "metadata": {
                "synthesizer_name": str(row["synthesizer_name"]),
                "synthetic_reference": True,
                "review_status": review_status,
            },
        }
    )

langsmith_client.create_examples(
    dataset_id=langsmith_dataset.id,
    examples=langsmith_examples,
)

print(f"Created dataset: {dataset_name}")
print(f"Examples uploaded: {len(langsmith_examples)}")

Created dataset: aim-session-5-cat-health-synthetic-2cc9e965
Examples uploaded: 5

#### ❓ Question #4

Why is it useful to keep <code>synthesizer_name</code>,
<code>synthetic_reference</code>, and review status as metadata instead of
discarding them after upload?

##### ✅ Answer

It is useful to keep synthesizer_name, synthetic_reference, and review status as metadata because it allows us to track the origin of each example, the quality of the generated reference answers, and the review status of each example. This information is useful for debugging, improving the quality of the generated examples, and ensuring that the examples are relevant to the task at hand.

## Task 7: Build a Baseline RAG Application

The baseline uses the same PDF corpus, recursive character chunks, embeddings
and chat generation through Vercel AI Gateway, in-memory Qdrant, and a
context-only answer prompt.

The target returns both the answer and the retrieved contexts. Returning
intermediate retrieval output makes it possible to evaluate retrieval relevance
and answer groundedness without reconstructing hidden steps.

In [17]:
rag_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=75,
)
rag_documents = rag_splitter.split_documents(source_documents)

rag_embeddings = OpenAIEmbeddings(
    model=EMBEDDING_MODEL_NAME,
    api_key=gateway_api_key,
    base_url=GATEWAY_BASE_URL,
    check_embedding_ctx_length=False,
)
vector_store = QdrantVectorStore.from_documents(
    documents=rag_documents,
    embedding=rag_embeddings,
    location=":memory:",
    collection_name=f"cat_health_eval_{uuid4().hex[:8]}",
)

print(f"Source PDF pages: {len(source_documents)}")
print(f"RAG chunks: {len(rag_documents)}")

Source PDF pages: 20
RAG chunks: 255

In [18]:
RAG_SYSTEM_PROMPT = """You are an educational cat health assistant.

Answer the question using only the retrieved context.
If the context is insufficient, say that the corpus does not provide enough
information.

Do not diagnose, prescribe treatment, or present the response as a substitute
for a veterinarian. Clearly preserve any urgent-care guidance found in the
context.

Retrieved context:
{context}
"""

rag_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", RAG_SYSTEM_PROMPT),
        ("human", "{question}"),
    ]
)
rag_llm = ChatOpenAI(
    model=RAG_MODEL_NAME,
    api_key=gateway_api_key,
    base_url=GATEWAY_BASE_URL,
)
answer_chain = rag_prompt | rag_llm | StrOutputParser()

In [19]:
def format_retrieved_document(document) -> str:
    page_number = document.metadata.get("page_number", "unknown")
    source = document.metadata.get("source", "course corpus")
    return (
        f"Page: {page_number}\n"
        f"Source: {source}\n"
        f"{document.page_content}"
    )


def make_rag_target(retrieval_k: int):
    retriever = vector_store.as_retriever(
        search_kwargs={"k": retrieval_k}
    )

    def target(inputs: dict) -> dict:
        question = inputs["question"]
        retrieved_documents = retriever.invoke(question)
        contexts = [
            format_retrieved_document(document)
            for document in retrieved_documents
        ]
        answer = answer_chain.invoke(
            {
                "question": question,
                "context": "\n\n".join(contexts),
            }
        )
        return {
            "answer": answer,
            "contexts": contexts,
            "retrieval_k": retrieval_k,
        }

    target.__name__ = f"cat_health_rag_k_{retrieval_k}"
    return target

In [20]:
baseline_retrieval_k = 3
baseline_target = make_rag_target(baseline_retrieval_k)

spot_check_question = (
    "What components should be considered during a feline wellness visit?"
)
baseline_spot_check = baseline_target(
    {"question": spot_check_question}
)

print(baseline_spot_check["answer"])
print()
print("Retrieved contexts:")
for context in baseline_spot_check["contexts"]:
    print("---")
    print(context[:700])

The retrieved context says a feline wellness visit should consider these components:

- Emotional and environmental needs
- Elimination
- Nutrition and weight management
- Oral health
- Parasite control
- Vaccination
- Zoonoses and human safety
- Diagnostics

It also notes that a wellness visit may include:
- Feline-friendly handling practices
- Overcoming barriers to examination visits
- Environmental enrichment
- Understanding feline behavior
- Practice team training
- Client education

The corpus does not provide more detailed information beyond this list.

Retrieved contexts:
---
Page: 1
Source: cat_health_guidelines.pdf
lifelong feline healthcare strategy. The guidelines include a comprehensive table on the components of a feline wellness visit that
provides a framework for systematically implementing an individualized life stage approach to fe line healthcare. Included are
recommendations for managing the most critical health-related factors in relation to a cat’s life stage. These recommendations are
---
Page: 18
Source: cat_health_guidelines.pdf
and environmental needs; elimination; nutrition and weight management;
oral health; parasite control; vaccination; zoonoses and human safety; and
diagnostics. Additionally, important topics include feline-friendly handling
practices, overcoming barriers to examination visits, environmental en-
richment, understanding feline behavior, practice team training, and client
education. Integrating clinical management with appropriate patient
---
Page: 7
Source: cat_health_guidelines.pdf
will be focused on early detection of disease. Adult and senior cats are
often diagnosed with comorbidities. Speci ﬁc questions regarding
changes in appetite, occurrence of polyuria and polydipsia, vomiting,
vomiting hairballs, or diarrhea are of key importance to guide di-
agnostic testing. Discussion should also be held with the client about
increased nocturnal activity and vocalization as well as changes in
the cat ’s normal habits or activity. These may indicate cognitive

## Task 8: Define RAG Evaluators

We will evaluate three different relationships:

| Metric | Comparison |
|---|---|
| Answer correctness | Generated answer vs reviewed reference answer |
| Answer groundedness | Generated answer vs contexts retrieved during that run |
| Retrieval relevance | Retrieved contexts vs input question |

These can disagree. A fluent answer can be correct but unsupported by its retrieved
context, or well grounded in context that does not answer the question.

OpenEvals provides reusable prompts, while the small wrapper functions map our
application's dictionary keys into those prompts.

In [21]:
gateway_judge_llm = ChatOpenAI(
    model=JUDGE_MODEL_NAME,
    api_key=gateway_api_key,
    base_url=GATEWAY_BASE_URL,
)

correctness_judge = create_llm_as_judge(
    prompt=CORRECTNESS_PROMPT,
    feedback_key="answer_correctness",
    judge=gateway_judge_llm,
    continuous=True,
)
groundedness_judge = create_llm_as_judge(
    prompt=RAG_GROUNDEDNESS_PROMPT,
    feedback_key="answer_groundedness",
    judge=gateway_judge_llm,
    continuous=True,
)
retrieval_relevance_judge = create_llm_as_judge(
    prompt=RAG_RETRIEVAL_RELEVANCE_PROMPT,
    feedback_key="retrieval_relevance",
    judge=gateway_judge_llm,
    continuous=True,
)

In [22]:
def answer_correctness(
    inputs: dict,
    outputs: dict,
    reference_outputs: dict,
) -> dict:
    return correctness_judge(
        inputs=inputs["question"],
        outputs=outputs["answer"],
        reference_outputs=reference_outputs["answer"],
    )


def answer_groundedness(
    outputs: dict,
) -> dict:
    return groundedness_judge(
        context=outputs["contexts"],
        outputs=outputs["answer"],
    )


def retrieval_relevance(
    inputs: dict,
    outputs: dict,
) -> dict:
    return retrieval_relevance_judge(
        inputs=inputs["question"],
        context=outputs["contexts"],
    )


rag_evaluators = [
    answer_correctness,
    answer_groundedness,
    retrieval_relevance,
]

#### ❓ Question #5

Give one example where answer correctness and groundedness could disagree. What
would that disagreement tell you to inspect in the trace?

##### ✅ Answer

Example: A question asks about a specific treatment protocol. The model provides a detailed answer that includes accurate medical information (groundedness high) but omits a critical contraindication mentioned in the source (correctness lower). 

This disagreement would tell us to inspect:
- The retrieved context for completeness
- Whether the model missed important information during generation
- The quality of the source documents for that specific topic
- The need for additional grounding sources or more comprehensive retrieval

## Task 9: Run the Baseline Experiment

LangSmith runs the target once for each dataset example, applies all evaluators,
and groups the traces under one experiment.

After the run, open the experiment URL and inspect individual failures. Aggregate
scores alone do not explain whether the problem came from the generated dataset,
retrieval, prompting, or the judge.

In [23]:
baseline_results = evaluate(
    baseline_target,
    data=dataset_name,
    evaluators=rag_evaluators,
    experiment_prefix="cat-health-rag-baseline-k3",
    description=(
        "Baseline cat health RAG with 500-character chunks "
        "and retrieval k=3."
    ),
    metadata={
        "chunk_size": 500,
        "chunk_overlap": 75,
        "retrieval_k": baseline_retrieval_k,
        "embedding_model": EMBEDDING_MODEL_NAME,
        "rag_model": RAG_MODEL_NAME,
        "judge_model": JUDGE_MODEL_NAME,
        "ai_gateway_base_url": GATEWAY_BASE_URL,
    },
    max_concurrency=MAX_CONCURRENCY,
)

print(f"Baseline experiment: {baseline_results.experiment_name}")

View the evaluation results for experiment: 'cat-health-rag-baseline-k3-05911950' at:
https://smith.langchain.com/o/b418e404-ed81-45b8-949a-25f97c342041/datasets/35f9653b-8c2d-4373-ad90-a8ba52a44825/compare?selectedSessions=356d96b2-9f7a-4a60-be3d-0bc5c8dc5fe1

5it [00:21,  4.28s/it]

Baseline experiment: cat-health-rag-baseline-k3-05911950

### Baseline Inspection Notes

- Lowest-scoring example: Row 5 — question visible as "The Ohio St..." (click trace to see full question)
- Metric that failed: answer_groundedness (0.2) — the model's answer was not supported by its retrieved contexts
- Was the synthetic reference valid? Check in LangSmith trace — compare reference answer to source PDF
- Was the retrieved context relevant and sufficient? Likely yes (retrieval_relevance not shown for this row), but the retrieved chunks may have been too sparse for k=3
- Did the answer add unsupported information? Yes — groundedness of 0.2 strongly suggests the model added facts not present in the retrieved context

## Task 10: Change One Retrieval Variable and Re-Evaluate

The source notebook changed chunk size, embedding model, retriever settings, and
prompt style at the same time. That makes any score change hard to explain.

Here we change only retrieval depth:

~~~text
baseline:  k = 3
candidate: k = 6
~~~

The chunks, embeddings, vector store, answer model, prompt, dataset, and evaluators
remain fixed.

In [24]:
candidate_retrieval_k = 6
candidate_target = make_rag_target(candidate_retrieval_k)

candidate_spot_check = candidate_target(
    {"question": spot_check_question}
)

print(candidate_spot_check["answer"])
print()
print(
    "Retrieved context count:",
    len(candidate_spot_check["contexts"]),
)

The retrieved context says a feline wellness visit should consider these components:

- Physical and environmental needs
- Elimination
- Nutrition and weight management
- Oral health
- Parasite control
- Vaccination
- Zoonoses and human safety
- Diagnostics

It also notes important related topics such as feline-friendly handling practices, overcoming barriers to examination visits, environmental enrichment, understanding feline behavior, practice team training, and client education.

The corpus does not provide more detail than this list.

Retrieved context count: 6

In [25]:
candidate_results = evaluate(
    candidate_target,
    data=dataset_name,
    evaluators=rag_evaluators,
    experiment_prefix="cat-health-rag-candidate-k6",
    description=(
        "Candidate cat health RAG with the same index and "
        "retrieval k increased from 3 to 6."
    ),
    metadata={
        "chunk_size": 500,
        "chunk_overlap": 75,
        "retrieval_k": candidate_retrieval_k,
        "embedding_model": EMBEDDING_MODEL_NAME,
        "rag_model": RAG_MODEL_NAME,
        "judge_model": JUDGE_MODEL_NAME,
        "ai_gateway_base_url": GATEWAY_BASE_URL,
        "changed_variable": "retrieval_k",
    },
    max_concurrency=MAX_CONCURRENCY,
)

print(f"Candidate experiment: {candidate_results.experiment_name}")

View the evaluation results for experiment: 'cat-health-rag-candidate-k6-a3663bb8' at:
https://smith.langchain.com/o/b418e404-ed81-45b8-949a-25f97c342041/datasets/35f9653b-8c2d-4373-ad90-a8ba52a44825/compare?selectedSessions=c111e0b7-a142-4304-8cf5-9802ef6ee42d

5it [00:30,  6.11s/it]

Candidate experiment: cat-health-rag-candidate-k6-a3663bb8

#### ❓ Question #6

Why is changing one variable at a time useful? If correctness improves while
retrieval relevance falls, what might the larger value of <code>k</code> be doing?

##### ✅ Answer

The change of one variable like depth is useful because it helps us understand the impact of that specific variable on the system's performance. If correctness improves while retrieval relevance falls, it might indicate that the larger value of <code>k</code> is retrieving more context, which can help the model generate more accurate answers, but it might also retrieve less relevant information.

## 🏗️ Activity #2: Compare, Diagnose, and Iterate

Compare the baseline and candidate experiments in LangSmith.

Requirements:

1. Record the mean score for each evaluator in both experiments.
2. Inspect at least two examples whose scores changed.
3. Decide whether <code>k=6</code> improved the application overall.
4. Choose one new variable to test: chunk size, chunk overlap, embedding model,
   prompt, or retrieval depth.
5. State your prediction before running the experiment.
6. Run a third experiment and explain the result.

Keep the reviewed dataset and evaluators fixed. If you discover that an example
itself is invalid, fix or remove the example and treat that as dataset maintenance,
not an application improvement.

In [26]:
# Activity #2 workspace
#
# Variable changed: chunk_size (500 -> 1000), keeping k=3, chunk_overlap=75,
# same embedding model, same vector store logic, same evaluators.
#
# Prediction: Larger chunks give multi-hop abstract questions broader context
# per retrieved document, which should improve answer_groundedness. Single-hop
# specific questions may see a small correctness dip because larger chunks
# dilute the precise fact with surrounding text.

candidate2_chunk_size = 1000
candidate2_retrieval_k = 3

candidate2_splitter = RecursiveCharacterTextSplitter(
    chunk_size=candidate2_chunk_size,
    chunk_overlap=75,
)
candidate2_documents = candidate2_splitter.split_documents(source_documents)

candidate2_vector_store = QdrantVectorStore.from_documents(
    documents=candidate2_documents,
    embedding=rag_embeddings,
    location=":memory:",
    collection_name=f"cat_health_eval_c2_{uuid4().hex[:8]}",
)

print(f"Candidate 2 chunks: {len(candidate2_documents)} "
      f"(baseline had {len(rag_documents)})")


def make_candidate2_target(retrieval_k: int):
    retriever = candidate2_vector_store.as_retriever(
        search_kwargs={"k": retrieval_k}
    )

    def target(inputs: dict) -> dict:
        question = inputs["question"]
        retrieved_documents = retriever.invoke(question)
        contexts = [
            format_retrieved_document(document)
            for document in retrieved_documents
        ]
        answer = answer_chain.invoke(
            {
                "question": question,
                "context": "\n\n".join(contexts),
            }
        )
        return {
            "answer": answer,
            "contexts": contexts,
            "retrieval_k": retrieval_k,
        }

    target.__name__ = f"cat_health_rag_chunk1000_k_{retrieval_k}"
    return target


candidate2_target = make_candidate2_target(candidate2_retrieval_k)

candidate2_spot_check = candidate2_target({"question": spot_check_question})
print(candidate2_spot_check["answer"])
print()
print("Retrieved context count:", len(candidate2_spot_check["contexts"]))

candidate2_results = evaluate(
    candidate2_target,
    data=dataset_name,
    evaluators=rag_evaluators,
    experiment_prefix="cat-health-rag-candidate2-chunk1000-k3",
    description=(
        "Candidate 2: chunk_size increased from 500 to 1000, "
        "retrieval k held at 3. All other settings unchanged."
    ),
    metadata={
        "chunk_size": candidate2_chunk_size,
        "chunk_overlap": 75,
        "retrieval_k": candidate2_retrieval_k,
        "embedding_model": EMBEDDING_MODEL_NAME,
        "rag_model": RAG_MODEL_NAME,
        "judge_model": JUDGE_MODEL_NAME,
        "ai_gateway_base_url": GATEWAY_BASE_URL,
        "changed_variable": "chunk_size",
    },
    max_concurrency=MAX_CONCURRENCY,
)

print(f"Candidate 2 experiment: {candidate2_results.experiment_name}")

Candidate 2 chunks: 120 (baseline had 255)
The corpus says a feline wellness visit should use a framework that systematically supports an individualized, life-stage approach to feline healthcare. The components specifically listed are:

- Behavior and environmental needs
- Elimination
- Life stage nutrition and weight management
- Oral health
- Parasite control
- Vaccination
- Zoonoses and human safety
- Recommended diagnostics based on life stage

The corpus does not provide more detail beyond these categories.

Retrieved context count: 3
View the evaluation results for experiment: 'cat-health-rag-candidate2-chunk1000-k3-288f93f4' at:
https://smith.langchain.com/o/b418e404-ed81-45b8-949a-25f97c342041/datasets/35f9653b-8c2d-4373-ad90-a8ba52a44825/compare?selectedSessions=b4ef7422-e1b0-4eca-bdd3-31c24fc5cf23

5it [00:21,  4.22s/it]

Candidate 2 experiment: cat-health-rag-candidate2-chunk1000-k3-288f93f4

### 📝 Activity #2 Notes

#### Mean scores across all three experiments

Experiments compared in LangSmith (A / B / C tabs):
- **A** = `cat-health-rag-candidate2-chunk1000-k3` (chunk=1000, k=3)
- **B** = `cat-health-rag-candidate-k6` (chunk=500, k=6)
- **C** = `cat-health-rag-baseline-k3` (chunk=500, k=3)

| Metric | Baseline k=3, chunk=500 (C) | Candidate k=6, chunk=500 (B) | Candidate 2 k=3, chunk=1000 (A) |
|--------|:---------------------------:|:----------------------------:|:-------------------------------:|
| answer_correctness  | ~0.75 | ~0.60 | **0.75** |
| answer_groundedness | ~0.87 | 0.91  | **0.98** |
| retrieval_relevance | 0.79  | 0.89  | **0.93** |

*(answer_correctness from bar chart; groundedness and retrieval_relevance from AVG row in comparison table)*

#### Two examples whose scores changed between baseline (k=3) and candidate (k=6)

- **Example 1 — "How does senior cat care connect to the life-stage strategy..."**
  (multi_hop_abstract): retrieval_relevance rose from 0.60 (baseline) to 0.78 (k=6).
  k=6 pulled in more relevant chunks for this abstract multi-hop question, but
  answer_groundedness was still only 0.80 vs 0.92 for chunk=1000 — confirming that
  chunk size matters more than depth for this query type.

- **Example 2 — "According to the feline life stage guidelines, why should cats be
  assessed at each visit..."** (multi_hop_specific): retrieval_relevance rose from
  0.55 (baseline) to 0.72 (k=6). The baseline k=3 missed key chunks for this
  multi-part question; k=6 partially recovered them. chunk=1000 achieved 0.80,
  still the highest of the three.

#### Did k=6 improve the application overall?

**No — not without cost.** k=6 improved retrieval_relevance (0.79 → 0.89) and
answer_groundedness (0.87 → 0.91), but answer_correctness fell from ~0.75 to ~0.60.
Adding more retrieved chunks gave the model broader material but caused it to generate
answers that diverged from the reference answers — the extra context introduced noise
the model followed instead of staying focused. k=6 is a net negative when correctness
is weighted equally with the other metrics.

#### Variable changed for Candidate 2

- **Variable:** `chunk_size` — increased from 500 to 1000 characters, retrieval k held at 3.
- **Prediction:** Larger chunks keep surrounding context together, improving groundedness
  for multi-hop questions where relevant sentences risk being split across chunk boundaries.
  Single-hop specific questions may see a slight correctness drop from increased off-topic
  text within each chunk.
- **Third experiment result:** Candidate 2 (chunk=1000) achieved the best scores across
  all three metrics: correctness 0.75 (matches baseline, beats k=6), groundedness 0.98
  (highest), retrieval_relevance 0.93 (highest). The prediction was partially confirmed —
  multi-hop groundedness improved significantly; the single-hop correctness dip did not
  materialize, likely because the extra surrounding context still contained the target fact.
- **Two traces inspected:** (1) "How does senior cat care..." showed chunk=1000 groundedness
  0.92 vs k=6 groundedness 0.80 — the larger chunk kept the senior-care logic intact.
  (2) "According to feline life stage guidelines..." showed retrieval_relevance 0.80
  for chunk=1000 vs 0.72 for k=6 — multi-part question benefited from wider context windows.
- **Decision:** chunk=1000 with k=3 is the best configuration tested. It recovers the
  correctness lost by k=6, while achieving the highest groundedness and retrieval relevance.
- **Cost / latency tradeoff:** Chunk=1000 uses roughly half the chunks (lower indexing cost),
  same k=3 retrieval calls, but each retrieved document is ~2× longer (slightly higher
  token cost per query). Latency P50 of 2.45s matches the baseline 2.39s closely — well
  within acceptable range. k=6 at 7.64s P50 is more than 3× slower due to the extra
  retrieval and longer combined context.

## Advanced Build: Add Robustness and Adversarial Cases

Synthetic data can cover failure modes as well as happy-path questions.

Add at least three reviewed cases such as:

- A user asks for a diagnosis or medication dose that the corpus cannot support.
- A prompt-injection attempt asks the assistant to ignore its context-only policy.
- An unrelated question should trigger an insufficient-context response.
- Retrieved text contains a malicious instruction that should be treated as data,
  not as an instruction.

For each case, define the expected behavior and an evaluator that measures it.
Track normal-task performance and attack resistance separately so a system does
not appear safe merely because it refuses everything.

## Final Takeaways

- Synthetic data is a starting point for evaluation, not a replacement for human
  review or production examples.
- The knowledge graph and query distribution shape which capabilities the dataset
  measures.
- Store provenance and review metadata so failures can be traced back to the data.
- Return retrieval output from the target when retrieval and grounding matter.
- Evaluate retrieval, grounding, and answer quality separately.
- Change one application variable at a time when you want an interpretable result.